# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-5.4.2

# NOTE: If you generated this yaml from an unprivileged and rootless podman container on an SELinux
# enabled system, check the podman generate kube man page for steps to follow to ensure that your pod/container
# has the right permissions to access the volumes added.
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    bind-mount-options: /home/ykrods/OneDrive:Z
  creationTimestamp: "2025-06-12T03:20:59Z"
  labels:
    app: onedrive-pod
  name: onedrive-pod
spec:
  containers:
  - env:
    - name: TERM
      value: xterm
    image: docker.io/driveone/onedrive:edge
    name: onedrive
    securityContext:
      runAsGroup: 1000
      runAsUser: 1000
    stdin: true
    tty: true
    volumeMounts:
    - mountPath: /onedrive/data
      name: home-ykrods-onedrive-host-0
    - mountPath: /onedrive/conf
      name: onedrive-conf-pvc
  volumes:
  - hostPath:
      path: /home/ykrods/OneDrive
      type: Directory
    name: home-ykrods-onedrive-host-0
  - name: onedrive-conf-pvc
    persistentVolumeClaim:
      claimName: onedrive-conf
